# Change these first
owner: hhftechnology # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: HHF Forum
    url: https://forum.hhf.technology
  - name: HHF Git
    url: https://git.hhf.technology
  - name: HHF Cheat-Sheet
    url: https://cheetsheet.hhf.technology
  - name: HHF Notes
    url: https://notes.hhf.technology/
  - name: HHF Firewall API
    url: $HHF_FIREWALL_API
  - name: HHF Node 1
    url: $HHF_NODE_1
  - name: HHF Node 2
    url: $HHF_NODE_2
  - name: HHF Node 3
    url: $HHF_NODE_3
  - name: HHF Database Cluster Node 1
    url: $HHF_DATABASE_CLUSTER_NODE_1
  - name: HHF Database Cluster Node 2
    url: $HHF_DATABASE_CLUSTER_NODE_2
  - name: HHF Database Cluster Node 3
    url: $HHF_DATABASE_CLUSTER_NODE_3
  - name: HHF HA Proxy Cluster Node 1
    url: $HHF_HA_PROXY_CLUSTER_NODE_1
  - name: HHF HA Proxy Cluster Node 2
    url: $HHF_HA_PROXY_CLUSTER_NODE_2
  - name: HHF HA Proxy Cluster Node 3
    url: $HHF_HA_PROXY_CLUSTER_NODE_3
  - name: HHF Podman Node 1
    url: $HHF_PODMAN_NODE_1
  - name: HHF_Podman_Node 2
    url: $HHF_PODMAN_NODE_2


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hhf.technology
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: hhf services status
  introTitle: "**HHF Technology Status** is the uptime monitor and status page, powered entirely by GitHub."
  introMessage: Welcome to HHF Technology Status This page provides real-time and historical information about the operational status of HHF Technology's services and infrastructure. Here you can monitor the availability and performance of our systems, view incident history, and subscribe to updates.
  navbar:
    - title: Status
      href: /
    - title: Forum
      href: https://forum.hhf.technology
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
